"""create_table_for_pbac

Revision ID: c39f2770c874
Revises: 
Create Date: 2024-11-14 11:47:41.793703+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c39f2770c874'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=32), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=32), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=32), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=105), nullable=False, comment='Tên'),
    sa.Column('last_name', sa.VARCHAR(length=105), nullable=False, comment='Họ'),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True, comment='Email'),
    sa.Column('phone', sa.VARCHAR(length=12), nullable=True, comment='Số điện thoại'),
    sa.Column('username', sa.VARCHAR(length=50), nullable=True, comment='tên tài khoản'),
    sa.Column('gender', sa.Boolean(), nullable=True),
    sa.Column('password', sa.VARCHAR(length=100), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('role_permissions',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=32), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role_id', sa.VARCHAR(length=32), nullable=True),
    sa.Column('permission_id', sa.VARCHAR(length=32), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=32), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=32), nullable=True),
    sa.Column('role_id', sa.VARCHAR(length=32), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
