"""add_history_login_and_black_list_token

Revision ID: 6d889407e049
Revises: c39f2770c874
Create Date: 2024-11-15 10:42:03.739638+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d889407e049'
down_revision: Union[str, None] = 'c39f2770c874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=32), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('jti', sa.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_table('login_history',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=32), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(), nullable=True),
    sa.Column('device_info', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('access_token', sa.VARCHAR(), nullable=True),
    sa.Column('refresh_token', sa.VARCHAR(), nullable=True),
    sa.Column('jti', sa.VARCHAR(length=32), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_history')
    op.drop_table('token_blacklist')
    # ### end Alembic commands ###
