"""create_table_customer_company

Revision ID: 871b869307e0
Revises: 
Create Date: 2024-08-09 11:42:26.490001+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '871b869307e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=32), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=105), nullable=False, comment='Tên công ty'),
    sa.Column('address', sa.VARCHAR(length=100), nullable=True, comment='Địa chỉ công ty'),
    sa.Column('phone', sa.VARCHAR(length=12), nullable=True, comment='Số điện thoại'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=32), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=105), nullable=False, comment='Tên đầy đủ'),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True, comment='Email'),
    sa.Column('phone', sa.VARCHAR(length=12), nullable=True, comment='Số điện thoại'),
    sa.Column('username', sa.VARCHAR(length=50), nullable=True, comment='tên tài khoản'),
    sa.Column('gender', sa.VARCHAR(length=10), nullable=True),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    op.drop_table('company')
    # ### end Alembic commands ###
